name: Unity Auto-Build and Release with Changelog

on:
  push:
    branches:
      - master  # or master

jobs:
  build:
    name: Auto Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - StandaloneLinux64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required to access full git history

    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}
        unityVersion: auto  # optional; builder can detect version

    - name: Compress Build
      run: |
        mkdir -p release
        zip -r release/${{ matrix.targetPlatform }}.zip build/${{ matrix.targetPlatform }}

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.versioning.outputs.tag }}
        name: Release ${{ steps.versioning.outputs.tag }}
        body: ${{ steps.versioning.outputs.changelog }}
        files: release/${{ matrix.targetPlatform }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
